### ISSUE TITLE
Demonstrate ability to harvest from THREDDS into IOOS WAF

### ISSUE THREAD

**Issue by lukecampbell** [ioos/ckanext-ioos-theme#1]

**Comment by rsignell-usgs** [comment]
@lukecampbell , I assume you'll be using the thredds crawler code at
https://github.com/asascience-open/thredds_crawler
right?

I think it would be useful to move this code from asascience-open to the ioos org, so that we could help move this forward as a community.   

@dpsnowden , do you agree?

**Comment by lukecampbell** [comment]
I do use thredds_crawler, yes.

**Comment by dpsnowden** [comment]
Yeah, I agree about hosting it at the IOOS org.  I think everyone would find this useful.

**Comment by rsignell-usgs** [comment]
@lukecampbell , I've temporarily made you an owner of IOOS, so you can transfer the repo.   You've probably done this before, but you just go to repo settings and scroll to the bottom "Danger Zone" and click on transfer.

**Comment by lukecampbell** [comment]
I don't need to be an owner to create repos. I made one http://github.com/ioos/thredds-crawler/

**Comment by lukecampbell** [comment]
We need to keep the asascience-open one there as several existing projects depend on it being there and being reachable.

**Comment by kwilcox** [comment]
So this got moved... but it was changed from using an underscore to a dash in the repository name (an OK change but not documented anywhere). Also, none of the files were updated to reflect the repository switch. Is someone working on this still or should I fix?

**Comment by daf** [comment]
@lukecampbell, you should transfer the repo from asascience-open, then fork it to asascience-open to keep proper linkage in place.

**Comment by daf** [comment]
(also, github is mad smart about moving repos, and keeps forwards in place.  so if you transfer to ioos, and then tried to git clone github.com/asascience-open/thredds_crawler, it would know how to find it still)

**Comment by lukecampbell** [comment]
Actually after talking with folks here, we'd rather not move it. IOOS or you folks are free to fork the existing repo.

**Comment by rsignell-usgs** [comment]
What is the rationale for not moving it?

**Comment by benjwadams** [comment]
Can we please move discussion re. moving thredds-crawler to IOOS to the GitHub issues of the its current repo that it's in just so we can keep things separated relative to their respective project?

**Comment by lukecampbell** [comment]
I think we're going to hold off on THREDDS harvesting for a while. There's a chance that Unidata will release a command-line version of NcISO that is up-to-date with the main fork of the project and we could leverage that instead of writing something else.

**Comment by rsignell-usgs** [comment]
Oh, interesting, I thought this issue was about harvesting ISO records from THREDDS catalogs that have the ncISO service enabled, so that command-line version of ncISO would be moot.

**Comment by mwengren** [comment]
I think the planned approach to that would be RA data manager would use ncISO to generate a WAF of (hopefully) valid ISO metadata that would then be registered as a harvest source in our upcoming Catalog registry system and then harvested by CKAN.   The idea is this will help avoid TDS catalog traversals and excessive granularity in metadata content in a direct TDS harvest, with more local knowledge of the server content by the data manager to create appropriate aggregations.  @lukecampbell can correct if I'm wrong.

**Comment by rsignell-usgs** [comment]
I thought this was the vision also.    I didn't read the subject of this issue carefully and thought it was kind of a "best practices" concept for the RA data managers -- so they could have scripts to create their WAFs from THREDDS catalogs.

**Comment by lukecampbell** [comment]
That's affirmative and the current plan.
