### ISSUE TITLE
CKAN Date/Time JavaScript UI broken

### ISSUE THREAD

**Issue by mwengren** [ioos/ckanext-ioos-theme#242]
The 'Start time' and 'End time' UI inputs used to display a JavaScript calendar widget that would allow selection of a date and time to input into the selection form.

In CKAN 2.9, it's broken.  Need to re-enable with some frontend troubleshooting.

**Comment by mwengren** [comment]
At the last meeting on 6/5, we decided that the solution was to get @nguyandy to look at this.  Has that happened yet?

**Comment by mwengren** [comment]
Now seeing a clear dates issue.  Hitting the clear and apply buttons doesn't work as expected.

**Comment by benjwadams** [comment]
Clear now working after #250 applied.  Closing.

**Comment by mwengren** [comment]
The date filter looks to be broken again.  No filtering of datasets takes place when values are selected and hit 'Apply'.

Depth filter appears to be failing also.

**Comment by mwengren** [comment]
@benjwadams says repeating the process to reload/rebuild the CKAN SOLR indexes following the custom process he developed as a workaround to CKAN's handling of SOLR.

This should hopefully address the filter issues being experienced.

**Comment by benjwadams** [comment]
Appears now working.  Inputting a year, e.g. just "2024" results in internal server error, however.
