### ISSUE TITLE
Harvest jobs not configurable via UI

### ISSUE THREAD

**Issue by mwengren** [ioos/ckanext-ioos-theme#247]
If I attempt to set a harvest source to manual, for example: 

https://data.ioos.us/harvest/edit/gcoos-erddap-biological

and click Save, the setting appears to be updated in the CKAN UI.  

However, there are still multiple (sometimes up to 3) harvests that run for this GCOOS harvest source per day according to the job logs:

https://data.ioos.us/harvest/gcoos-erddap-biological/job

If a harvest source is set to 'Manual', it should only run when manually triggered.  

Similarly, if it's set to 'Daily', it should only run 1x per day (not 2 or 3x/day).  

We need to figure out why the harvest jobs are not running according to the CKAN settings and fix to be configurable via UI.

**Comment by mwengren** [comment]
xref harvest monitoring script: https://github.com/ioos/catalog-docker-base/blob/master/contrib/scripts/clear_stuck_harvests.bash

**Comment by mwengren** [comment]
Harvest jobs are still running on a frequency > daily, regardless of what is configured in the CKAN UI.  

We tested again with the GCOOS ERDDAP Biological WAF set to Manual, confirmed this is propagated to the database, however there are still routine harvest jobs running.  

@benjwadams to look into further troubleshooting.

**Comment by mwengren** [comment]
@benjwadams I believe this issue is still present as of our Catalog meeting today if you're able to look into now that funding is once again available.

**Comment by mwengren** [comment]
@benjwadams Once #238 is resolved, can you re-investigate this one?  Harvest job UI settings don't seem to be persisted or respected by the CKAN harvesters.

**Comment by benjwadams** [comment]
This is likely due to `ckan harvester job-all`  https://github.com/ioos/catalog-docker-base/blob/main/contrib/scripts/clear_stuck_harvests.bash#L9 being issued on the stuck job cleanup script.  I'm testing removing just this line and think this will fix things.

**Comment by mwengren** [comment]
@benjwadams stated in https://github.com/ioos/ckanext-ioos-theme/issues/238#issuecomment-2007755461 that CKAN is honoring the harvest job configurations and this issue can be closed.
