### ISSUE TITLE
Catalog is having some SOLR and/or CSS UI issues currently

### ISSUE THREAD

**Issue by mwengren** [ioos/ckanext-ioos-theme#254]
At present the SOLR faceted search UI is broken/empty: 

![Screenshot 2024-06-10 12 44 01](https://github.com/ioos/ckanext-ioos-theme/assets/1469921/32c8aed3-a465-4a75-860d-0d4cc898f7cd)

There are also some CSS issues popping up in various UI elements.  

Dataset content (sub-element tabs): 

![Screenshot 2024-06-10 12 44 54](https://github.com/ioos/ckanext-ioos-theme/assets/1469921/ad1e9975-3732-4076-ad67-761f37921de9)

Homepage:

![Screenshot 2024-06-10 13 00 08](https://github.com/ioos/ckanext-ioos-theme/assets/1469921/943beaa0-8fea-4441-96cc-73e065624d34)

Footer:

![Screenshot 2024-06-10 13 02 13](https://github.com/ioos/ckanext-ioos-theme/assets/1469921/e4b8f9ad-1b6d-4e5f-80ff-26f5cac0491f)

**Comment by benjwadams** [comment]
Not sure what changed, as CSS hasn't been modified recently.

As part of the feedback commits, I also addressed some of the broken styling for GCMD Keyword hierarchy in https://github.com/ioos/ckanext-ioos-theme/commit/fd4995571b065cb2f35744e2b457c584877166c1

**Comment by benjwadams** [comment]
Interface for `get_facet_items_dict` changed in CKAN 2.10.4 and now requires facets to be passed in explicitly.  The facets themselves were being fetched from Solr, but weren't sent to the templates properly.

This has been addressed and now search facets are properly populating on the page.
