### ISSUE TITLE
CKAN Spatial search/filter is failing

### ISSUE THREAD

**Issue by mwengren** [ioos/ckanext-ioos-theme#260]
To reproduce:

Select a bounding box from the spatial search/filter control on the Datasets page, then click 'Apply'.

The results on the Datasets page are as follows:

```
Error
There was an error while searching. Please try again.
```

**Comment by benjwadams** [comment]
Seems to have occurred when upgraded to CKAN 2.10.5:


Fix here is not yet merged into `ckanext-spatial`, essentially you need to limit Solr to `field` queries:
https://github.com/ckan/ckanext-spatial/issues/328

**Comment by benjwadams** [comment]
Search filter works again after upgrades made in https://github.com/ioos/catalog-docker-base/commit/8224f7ff2fbe681a13e342358f6d21192950a57d
