### ISSUE TITLE
Update dataset metadata link in the Data & Resources section to remove IOOS Registry references

### ISSUE THREAD

**Issue by mwengren** [ioos/ckanext-ioos-theme#263]
### What should we add?

Change the label for `ISO-19139 (IOOS Registry)` metadata to:

`ISO-19139 (Source) Metadata` 

with subtitle: `The source XML content harvested by CKAN` 

to better reflect current function of the IOOS Catalog.  We no longer harvest metadata from the IOOS Registry, it comes from a variety of data provider sources.

After changes, there should be two metadata links at the bottom of each dataset:

* `ISO-19139 (Local) Metadata`
* `ISO-19139 (Source) Metadata`

### Reference

Current configuration: 

![Image](https://github.com/user-attachments/assets/499b9404-0720-4ffe-8de5-ff717ba6badb)

**Comment by benjwadams** [comment]
There's only one metadata link now.
