### ISSUE TITLE
UI: GCMD Keyword and CF Standard Name faceted filter controls not displaying properly

### ISSUE THREAD

**Issue by mwengren** [ioos/ckanext-ioos-theme#268]
### What went wrong?

Something is up with the SOLR index and filtering/parsing rules for the CF Standard Name and GCMD Keyword faceted filtering UI controls on the sidebar.  

Previously, each element of the facets would include one term.  Presently, there are some that include multiple terms appended together.  There may be some sort of error in the parsing rules used in the SOLR index?

Screenshot attached.   The `[` and `"` characters shouldn't be visible, only the terms themselves.

![Image](https://github.com/user-attachments/assets/9908551a-2726-406b-82a7-b9cc93c54887)

### Operating System

Windows

### Version

N/A

### Python Version

N/A

### Code to Reproduce

```python
N/A
```

### Errors, Traceback, and Logs

```pytb

```

**Comment by benjwadams** [comment]
Fixed by https://github.com/ioos/ckanext-ioos-theme/commit/743af64e997cf3fc4dc3a822c4fd2f53203eb1b0 and subsequent search index reindex.  Method names changed in CKAN 2.10.
